### ISSUE TITLE
Errore nel parsing di <numero><op> -<numero2>

### ISSUE THREAD

**Issue by NeroReflex** [gianluca-nitti/java-expr-eval#1]
Alla richiesta di parsing 5_-9 il risultato è: *Error while parsing expression: An expression was expected, but an operator was found_

Il risultato corretto si ottiene immettendo come input 5*(-9).

La situazione numero con segno negativo deve essere gestita in modo migliore: anche una semplice invocazione del risolutore con input un numero negativo produce un errore.

**Comment by gianluca-nitti** [comment]
Grazie della segnalazione. Sono al corrente che ci sono problemi di questo genere.
Il primo comunque non mi sembra un vero problema, di solito non si scrive `5*-9` ma `5*(-9)`; comunque proverò a sistemarlo ugualmente.
Non capisco invece
> una semplice invocazione del risolutore con input un numero negativo produce un errore

Se io eseguo `java -jar javaexpreval-1.1-SNAPSHOT.jar -3` ottengo `Result = -3.0` (con il jar della release 1.1).

**Comment by gianluca-nitti** [comment]
Ok, ho capito dov'è il problema: si verifica se l'espressione inizia con uno spazio; infatti nel bot con verbose funziona (che concatena gli args), mentre normalmente no (perchè chiama getMessage, che ritorna una stringa che inizia con uno spazio). In altre parole, `java -jar javaexpreval-1.1-SNAPSHOT.jar "-3"` funziona ma `java -jar javaexpreval-1.1-SNAPSHOT.jar " -3"` no.
Vedo di sistemare.

**Comment by gianluca-nitti** [comment]
Fixato tutto in a3d39e4735d7a927c90636c6f8658292ae597bdd.
(per quanto riguarda il PizzaBot le modifiche saranno incluse quando verrà rilasciata, a breve, la nuova versione 2.0 della libreria con il supporto completo alle variabili, che è in sviluppo).
